Error handling

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -128,10 +128,11 @@ jobs:
           echo "Target EC2 InstanceId: $INSTANCE_ID"
           echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
 
-      - name: Deploy Application
+      - name: Download Application
         run: |
           INSTANCE_ID="${{ env.INSTANCE_ID }}"
-
+          
+          echo "Downloading application artifacts to target. InstanceId: $INSTANCE_ID..."
           COMMAND_ID=$(aws ssm send-command \
             --instance-ids $INSTANCE_ID \
             --document-name "AWS-RunRemoteScript" \
@@ -144,6 +145,37 @@ jobs:
             --query "Command.CommandId" \
             --output text)
 
+          echo "Waiting for SSM Command to finish. CommandId: $COMMAND_ID"
+          aws ssm wait command-executed \
+            --command-id $COMMAND_ID \
+            --instance-id $INSTANCE_ID &> /dev/null || true
+
+          echo "SSM Command finished. Output:"
+          aws ssm get-command-invocation \
+              --command-id $COMMAND_ID \
+              --instance-id $INSTANCE_ID \
+              --query "{
+                STATUS: Status,
+                STDOUT: StandardOutputContent,
+                STDERR: StandardErrorContent
+              }" \
+              --output table
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id $COMMAND_ID \
+            --instance-id $INSTANCE_ID \
+            --query "Status" \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "Application download failed"
+            exit 1
+          fi;
+          echo "Application download succeeded!"
+
+      - name: Deploy Application
+        run: |
+          INSTANCE_ID="${{ env.INSTANCE_ID }}"
           echo "Reading application startup script: atx-pipeline/scripts/startup.sh"
           COMMANDS="["
           while IFS= read -r line; do 
